### ISSUE TITLE
Implement webhooks management

### ISSUE THREAD

**Issue by zugao** [projectsyn/component-appcat-service-postgresql#8]
The latest version of [appcat-postgresql](https://github.com/vshn/appcat-service-postgresql/releases/tag/provider-postgresql-0.1.7) uses validation webhooks which require certificates to work. Currently the chart is being installed with [predefined certificates](https://vshn.github.io/appcat-service-postgresql/appcat-service-postgresql/tutorials/installation.html) (step 4). This step has to be managed by the component.

Implementation ideas:
1) Component crafts a secret which references certificates from Vault. ArgoCD will populate that sensitive information from Vault to valid secret data during deployment. This new secret `webhook.existingSecret` needs to be available in the Helm Chart.
2) Add a pre-installation job for Argo to create the secret with self-signed certificates. We will still need `webhook.existingSecret` for that matter.

## Acceptance Criteria
* The secret should be created in the same namespace as the operator

## Notes
we need:
* argocd pre-hook
* bash code to create certificates
* a job definition to trigger the certificate creation
* use hardcoded name for the secret

**Comment by ccremer** [comment]
There are much easier ways for Openshift: https://docs.openshift.com/container-platform/4.10/security/certificates/service-serving-certificate.html (also supports patching Webhook configs)
And since our first target platform is Openshift anyway, that's good enough for now.

My vote is for going that route with service certificates, no need to script something in an ArgoCD job when not yet needed.

**Comment by Kidswiss** [comment]
I agree, but let's keep this open for when we want to support plain k8s.

**Comment by ccremer** [comment]
To support plain K8s in the future, we may consider https://github.com/projectsyn/k8s-service-ca-controller which is hopefully released by then.
